### ISSUE TITLE
Broken for python3.10

### ISSUE THREAD

**Issue by daleksic-godaddy** [godaddy/aws-okta-processor#46]
It fails to execute on python3.10

```
❯ aws-okta-processor --help
Traceback (most recent call last):
  File "/Users/dacha204/.local/bin/aws-okta-processor", line 5, in <module>
    from aws_okta_processor.cli import main
  File "/Users/dacha204/.local/pipx/venvs/aws-okta-processor/lib/python3.10/site-packages/aws_okta_processor/cli.py", line 25, in <module>
    from . import commands
  File "/Users/dacha204/.local/pipx/venvs/aws-okta-processor/lib/python3.10/site-packages/aws_okta_processor/commands/__init__.py", line 1, in <module>
    from . import authenticate # noqa
  File "/Users/dacha204/.local/pipx/venvs/aws-okta-processor/lib/python3.10/site-packages/aws_okta_processor/commands/authenticate.py", line 30, in <module>
    from aws_okta_processor.core.fetcher import SAMLFetcher
  File "/Users/dacha204/.local/pipx/venvs/aws-okta-processor/lib/python3.10/site-packages/aws_okta_processor/core/fetcher.py", line 5, in <module>
    import aws_okta_processor.core.prompt as prompt
  File "/Users/dacha204/.local/pipx/venvs/aws-okta-processor/lib/python3.10/site-packages/aws_okta_processor/core/prompt.py", line 4, in <module>
    from collections import Mapping
ImportError: cannot import name 'Mapping' from 'collections' (/usr/local/Cellar/python@3.10/3.10.0_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/collections/__init__.py)
```

It works fine on python3.9.

## Steps to reproduce:

```
brew install python@3.10
pipx install --python /usr/local/opt/python@3.10/bin/python3.10 aws-okta-processor
aws-okta-processor --help
```

**Comment by rwebler-godaddy** [comment]
I've changed the following line, locally
https://github.com/godaddy/aws-okta-processor/blob/7c5d98ee0f6f3f3d64d7bdf9eccae596406e06cc/aws_okta_processor/core/prompt.py#L4

to 
```py
from collections.abc import Mapping
```

and it's working with Python 3.10

**Comment by tarkatronic** [comment]
@rwebler-godaddy Thanks for checking into this! I'll see about providing a patch that does that in a backward-compatible fashion. 👍🏻
